language: node_js
node_js: '8.10.0'
branches:
   only:
      - workbox-sw
before_script:
   - npm install -g @angular/cli
   - npm install -g firebase-tools
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
