language: node_js
node_js: '8.10.0'
branches:
   only:
      - master
before_script:
   - npm install -g --silent firebase-tools
script:
  - npm run workbox-build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
